server:
  port: 8080

jwt:
  secret: zluteprasatkoslodolesa585858.
  secretRefresh: jelenkopadomice4455+

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tomas.svojanovsky33@gmail.com
    password: ytevtheyemrhhfpp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: postgres://bygsgwumjuxuyh:e3a0aa9f9241fc6ee5def2531e51511611cdef622122329125aee547560ec740@ec2-52-30-159-47.eu-west-1.compute.amazonaws.com:5432/dfi8083vegms6
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

