server:
  port: 8080

jwt:
  secret: zluteprasatkoslodolesa585858.
  secretRefresh: jelenkopadomice4455+

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    path: /api-docs-ui.html

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tomas.svojanovsky33@gmail.com
    password: ytevtheyemrhhfpp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/todolist
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  devtools:
    livereload:
      enabled: true

